import test from 'node:test';
import assert from 'node:assert/strict';
import { newRoom, newBlock, duplicateRoom, validateRoom, parseImport, safeUrl } from '../src/core/model.js';
import { checkAnswer } from '../src/core/answers.js';
import { isUnlocked, assignedMembers, isComplete } from '../src/core/conditions.js';
import { createTestSession, submitAnswer, revealHint, recordComplete, blockAvailable, sessionSummary } from '../src/core/session.js';
import { LocalRepository } from '../src/data/storage.js';
import { exampleRoom } from '../src/data/examples.js';

test('example is valid and uses independent content identifiers', () => {
  const r = exampleRoom(); assert.deepEqual(validateRoom(r), []); assert.notEqual(r.id, exampleRoom().id);
});
test('duplicate remaps condition references and allocates new identity', () => {
  const r = exampleRoom(); r.content[1].unlock.conditions = [{ blockId: r.content[0].id, event: 'button', member: 1 }];
  const c = duplicateRoom(r); assert.notEqual(c.id, r.id); assert.notEqual(c.content[0].id, r.content[0].id);
  assert.equal(c.content[1].unlock.conditions[0].blockId, c.content[0].id); assert.deepEqual(validateRoom(c), []);
});
test('import rejects invalid versions, duplicate ids, missing and cyclic references', () => {
  assert.throws(() => parseImport('{}'));
  const r = exampleRoom(); r.content[1].id = r.content[0].id; assert.match(validateRoom(r).join(), /중복/);
  const c = exampleRoom(); c.content[0].unlock.conditions = [{ blockId: c.content[1].id, event: 'complete' }]; c.content[1].unlock.conditions = [{ blockId: c.content[0].id, event: 'complete' }]; assert.match(validateRoom(c).join(), /순환/);
  c.content[1].unlock.conditions[0].blockId = 'missing'; assert.match(validateRoom(c).join(), /존재하지/);
});
test('text accepts multiple answers with configured normalization only', () => {
  const b = newBlock(); b.answers = ['glucose', '포도당']; assert.equal(checkAnswer(b, ' GLUCOSE '), true); assert.equal(checkAnswer(b, '포 도 당'), false);
  b.normalization.spaces = true; assert.equal(checkAnswer(b, '포 도 당'), true); b.normalization.punctuation = true; assert.equal(checkAnswer(b, '포도당!'), true);
  b.normalization.case = false; assert.equal(checkAnswer(b, 'Glucose'), false);
});
test('numbers are exact and reject empty or non-finite input', () => { const b = newBlock(); b.questionType = 'number'; b.answers = ['0', '2.5']; assert.equal(checkAnswer(b, ''), false); assert.equal(checkAnswer(b, '   '), false); assert.equal(checkAnswer(b, '0'), true); assert.equal(checkAnswer(b, '2.50'), true); assert.equal(checkAnswer(b, '2.5001'), false); assert.equal(checkAnswer(b, 'Infinity'), false); });
test('multi-select requires the exact set, order and match preserve order', () => { const b = newBlock(); b.answers = ['a', 'b']; b.questionType = 'multi'; assert.equal(checkAnswer(b, ['b', 'a']), true); assert.equal(checkAnswer(b, ['a', 'a']), false); assert.equal(checkAnswer(b, ['a']), false); for (const type of ['order', 'match']) { b.questionType = type; assert.equal(checkAnswer(b, ['a', 'b']), true); assert.equal(checkAnswer(b, ['b', 'a']), false); } });
test('approval and condition blocks cannot be solved by fabricated answer text', () => { const b = newBlock(); for (const type of ['approval', 'condition']) { b.questionType = type; b.answers = ['yes']; assert.equal(checkAnswer(b, 'yes'), false); } b.questionType = 'switch'; assert.equal(checkAnswer(b, true), true); assert.equal(checkAnswer(b, 'true'), false); });
test('conditions support AND/OR/N and filter member and role', () => { const conditions = [{ blockId: 'a', event: 'complete', member: 1 }, { blockId: 'b', event: 'button', role: '조장' }]; const events = [{ blockId: 'a', type: 'complete', member: 1 }]; assert.equal(isUnlocked({ mode: 'AND', conditions }, events), false); assert.equal(isUnlocked({ mode: 'OR', conditions }, events), true); assert.equal(isUnlocked({ mode: 'N', count: 2, conditions }, events), false); events.push({ blockId: 'b', type: 'button', role: '조장' }); assert.equal(isUnlocked({ mode: 'AND', conditions }, events), true); assert.equal(isUnlocked({ mode: 'N', count: 2, conditions }, events), true); });
test('auto assignment adapts to member count independently of roles', () => { const b = newBlock(), members = [{ member: 1, role: '조원' }, { member: 2, role: '조원' }, { member: 3, role: '조원' }]; b.assignment.mode = 'auto'; assert.equal(assignedMembers(b, members, 7)[0].member, 2); assert.equal(assignedMembers(b, members.slice(0, 2), 7)[0].member, 2); assert.equal(assignedMembers(b, members, 5)[0].member, 3); });
test('team completion does not count duplicate events or missing roles', () => { const b = newBlock(), members = [{ member: 1, role: '조원' }, { member: 2, role: '조원' }], events = [{ type: 'complete', blockId: b.id, member: 1 }, { type: 'complete', blockId: b.id, member: 1 }]; b.completion = { mode: 'n', count: 2 }; assert.equal(isComplete(b, events, members), false); b.completion = { mode: 'role', role: '조장' }; assert.equal(isComplete(b, events, members), false); b.completion = { mode: 'all' }; assert.equal(isComplete(b, events, members), false); events.push({ type: 'complete', blockId: b.id, member: 2 }); assert.equal(isComplete(b, events, members), true); });
test('full individual play records arrival once and never stores wrong answer strings', () => { const r = exampleRoom(), s = createTestSession(r, 1000); assert.equal(submitAnswer(r, s, r.content[1], 1, 'secret wrong input').ok, false); assert.equal(submitAnswer(r, s, r.content[0], 1, null, 2000).ok, true); submitAnswer(r, s, r.content[1], 1, 'secret wrong input'); assert.equal(JSON.stringify(s).includes('secret wrong input'), false); assert.equal(sessionSummary(r, s).wrong, 1); submitAnswer(r, s, r.content[1], 1, '포도당', 3000); submitAnswer(r, s, r.content[2], 1, '소장', 4000); submitAnswer(r, s, r.content[3], 1, '2413', 5000); assert.equal(s.finishedAt, 5000); recordComplete(r, s, r.content[3], 1, 'teacher-test', 6000); assert.equal(s.finishedAt, 5000); assert.equal(sessionSummary(r, s).score, 300); assert.equal(sessionSummary(r, s).seconds, 4); });
test('shared hint limit and penalties survive serialized test recovery', () => { const r = exampleRoom(); r.playMode = 'team'; r.rules.hints = 'team'; r.rules.hintLimit = 1; r.rules.hintPenalty = 20; const s = createTestSession(r); recordComplete(r, s, r.content[0], 1); revealHint(r, s, r.content[1], 1); assert.throws(() => revealHint(r, s, r.content[1], 2), /すべて|모두/); const restored = JSON.parse(JSON.stringify(s)); assert.equal(restored.penalties, 20); assert.equal(sessionSummary(r, restored).hints, 1); });
test('individual hint limits are isolated by member and stage limits by stage', () => { const r = exampleRoom(); r.playMode = 'team'; r.rules.hints = 'individual'; r.rules.hintLimit = 1; const s = createTestSession(r); recordComplete(r, s, r.content[0], 1); revealHint(r, s, r.content[1], 1); revealHint(r, s, r.content[1], 2); assert.equal(sessionSummary(r, s).hints, 2); assert.throws(() => revealHint(r, s, r.content[1], 1)); });
test('conditional blocks can open independently from sequential predecessors', () => { const r = exampleRoom(); const s = createTestSession(r); const b = r.content[3]; b.unlock.conditions = [{ blockId: r.content[0].id, event: 'button' }]; assert.equal(blockAvailable(r, s, b, 1), false); recordComplete(r, s, r.content[0], 1); assert.equal(blockAvailable(r, s, b, 1), true); });
test('local CRUD persists and fails visibly when storage is unavailable', async () => { const map = new Map(), storage = { getItem: k => map.get(k) || null, setItem: (k, v) => map.set(k, v) }; const repo = new LocalRepository(storage); const r = exampleRoom(); await repo.save(r); assert.equal((await repo.list()).length, 1); r.title = '수정'; await repo.save(r); assert.equal((await repo.list())[0].title, '수정'); await repo.remove(r.id); assert.equal((await repo.list()).length, 0); storage.setItem = () => { throw Error('quota'); }; await assert.rejects(repo.save(r), /저장 공간/); });
test('test reset preserves original content and fixed room code', () => { const r = exampleRoom(), original = JSON.stringify(r), s = createTestSession(r); recordComplete(r, s, r.content[0], 1); const fresh = createTestSession(r); assert.equal(fresh.events.length, 0); assert.equal(JSON.stringify(r), original); });
test('media URLs reject executable and embedded-data schemes', () => { assert.equal(safeUrl('javascript:alert(1)'), ''); assert.equal(safeUrl('data:image/png;base64,AA'), ''); assert.equal(safeUrl('https://example.com/a.png'), 'https://example.com/a.png'); });
test('unknown members cannot satisfy a team threshold', () => { const b = newBlock(); b.completion = { mode: 'n', count: 1 }; assert.equal(isComplete(b, [{ type: 'complete', blockId: b.id, member: 99 }], [{ member: 1, role: '조원' }]), false); });
test('JSON rejects negative penalties and impossible N conditions', () => { const r = exampleRoom(); r.rules.hintPenalty = -1; assert.match(validateRoom(r).join(), /페널티/); r.rules.hintPenalty = 0; r.content[1].unlock = { mode: 'N', count: 2, conditions: [{ blockId: r.content[0].id, event: 'complete' }] }; assert.match(validateRoom(r).join(), /조건 수/); });
test('stage hint quotas reset across different stages', () => { const r = exampleRoom(); r.rules.hints = 'stage'; r.rules.hintLimit = 1; r.content[2].stage = '2'; const s = createTestSession(r); recordComplete(r, s, r.content[0], 1); revealHint(r, s, r.content[1], 1); recordComplete(r, s, r.content[1], 1); assert.doesNotThrow(() => revealHint(r, s, r.content[2], 1)); assert.equal(sessionSummary(r, s).hints, 2); });
