import test from 'node:test';import assert from 'node:assert/strict';
import {newRoom,newBlock,normalizeRoom,duplicateRoom,ensureBlockQr,inspectForPlay} from '../src/core/model.js';
import {manualCode,ensureManualCodes} from '../src/core/qr.js';
import {createParallel} from '../src/core/parallel.js';
import {LobbyClient} from '../src/data/lobby.js';
import {stagingConfig} from '../scripts/load-backend.mjs';
test('load guard refuses production, missing opt-in and admin keys before any network request',()=>{
 const jwt=role=>'header.'+Buffer.from(JSON.stringify({role})).toString('base64url')+'.signature';
 const env={ESCAPE_LOAD_CONFIRM:'disposable-staging',ESCAPE_LOAD_URL:'https://fixture.supabase.co',ESCAPE_LOAD_ALLOW_HOST:'fixture.supabase.co',ESCAPE_LOAD_PUBLIC_KEY:'sb_publishable_fixture',ESCAPE_LOAD_TEACHER_JWT:jwt('authenticated')};
 assert.equal(stagingConfig(env).url.hostname,'fixture.supabase.co');assert.throws(()=>stagingConfig({}));
 assert.throws(()=>stagingConfig({...env,ESCAPE_LOAD_CONFIRM:''}));assert.throws(()=>stagingConfig({...env,ESCAPE_LOAD_URL:'https://rxknixllqewkvgfnpshu.supabase.co',ESCAPE_LOAD_ALLOW_HOST:'rxknixllqewkvgfnpshu.supabase.co'}));
 assert.throws(()=>stagingConfig({...env,ESCAPE_LOAD_PUBLIC_KEY:'sb_secret_admin'}));assert.throws(()=>stagingConfig({...env,ESCAPE_LOAD_PUBLIC_KEY:jwt('service_role')}));assert.throws(()=>stagingConfig({...env,ESCAPE_LOAD_TEACHER_JWT:jwt('service_role')}));
});
test('manual codes are independent, unique within a document, stable on normalization and do not alter printed tokens',()=>{const r=newRoom(),b=newBlock();b.questionType='qr';r.content=[b];const m=ensureBlockQr(r,b),token=m.codes[0].token;m.codes.push({...m.codes[0],id:crypto.randomUUID()});ensureManualCodes(r);assert.notEqual(m.codes[0].manualCode,m.codes[1].manualCode);assert.equal(m.codes[0].token,token);assert.deepEqual(normalizeRoom(r).qrMissions,r.qrMissions);assert.match(manualCode(),/^[A-HJ-NP-Z2-9]{6}$/);assert.notEqual(duplicateRoom(r).qrMissions[0].codes[0].manualCode,m.codes[0].manualCode);});
test('validation reports every issue by block ID even with identical titles',()=>{const r=newRoom(),a=newBlock(),b=newBlock('story');a.title=b.title='같은 제목';a.questionType='choice';a.options=['하나'];a.display='image';a.backgroundUrl='';r.content=[a,b];const report=inspectForPlay(r);assert(report.byBlock[a.id].filter(i=>i.severity==='error').length>=2);assert(report.byBlock[a.id].some(i=>i.severity==='warning'));assert.equal(report.byBlock[b.id].length,0);assert.equal(report.errors.length,report.issues.filter(i=>i.severity==='error').length);});
test('role, QR, chat and parallel problems retain precise references',()=>{const r=normalizeRoom(newRoom());r.playMode='team';Object.assign(r.teamSettings,{rolesEnabled:true,roleViewsEnabled:true,roles:['A','B']});const g=createParallel(r,r.stageGroups[0].id,newBlock),a=r.content[1];a.assignment.visibleRoles=['deleted'];a.chatEnabled=true;a.chatRoomIds=['deleted-chat'];a.type='question';a.questionType='qr';const m=ensureBlockQr(r,a);m.codes[0].active=false;const report=inspectForPlay(r);assert(report.byBlock[a.id].some(i=>i.message.includes('역할')));assert(report.byBlock[a.id].some(i=>i.message.includes('QR')));assert(report.byBlock[a.id].some(i=>i.message.includes('채팅방')));g.steps[0].cells[1].blockId='missing';assert(inspectForPlay(r).errors.some(s=>s.includes('병렬')));});
test('cyclic references map to their blocks; roster-dependent QR capacity is only a warning',()=>{const r=normalizeRoom(newRoom()),a=newBlock('story'),b=newBlock('story');r.content=[a,b];a.unlock.conditions=[{blockId:b.id,event:'complete'}];b.unlock.conditions=[{blockId:a.id,event:'complete'}];const report=inspectForPlay(r);assert(report.byBlock[a.id].some(i=>i.message.includes('순환')));assert(report.byBlock[b.id].some(i=>i.message.includes('순환')));const q=newBlock();q.questionType='qr';q.qrScope='team';r.content=[q];r.playMode='team';r.teamSettings.maxMembers=4;const m=ensureBlockQr(r,q);m.mode='UNIQUE_MEMBER';const qrReport=inspectForPlay(r);assert.equal(qrReport.errors.length,0);assert(qrReport.byBlock[q.id].some(i=>i.severity==='warning'&&i.message.includes('최대 인원')));});
test('new-device recovery is explicit, persists only its own token and keeps participant/session',async()=>{const data=new Map(),storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};let requests=[];const repo={config:{url:'https://fixture.supabase.co'},request:async(path,{body})=>{requests.push([path,body]);return path.endsWith('escape_join_lobby')?{requiresRecovery:true,challenge:'challenge'}:{participantId:'same-participant',sessionId:'same-session'};}};const client=new LobbyClient(repo,storage),identity={p_grade:2,p_class:1,p_number:1,p_name:'학생'};assert((await client.join('123456',identity)).requiresRecovery);assert(!client.saved('123456').participantId);await client.recover('123456','challenge');assert.equal(client.saved('123456').participantId,'same-participant');assert.equal(requests[0][1].p_token,requests[1][1].p_token);});
