import {diagnosticBadge} from './block-diagnostics.js';
import {parallelIds,parallelGroup,addParallelStep,laneRoles} from '../core/parallel.js';
import {roleNames,audienceRoles,roleVisible} from '../core/team-settings.js';
import {newBlock,BLOCK_TYPES,displayTypesFor} from '../core/model.js';
import {esc,options,confirmDialog,toast} from './dom.js';
export function parallelRowHtml(room,g,selected,roleFilter='',byBlock={}){return `<article class="parallel-row" draggable="true" data-block="${parallelIds(g)[0]}"><header><strong>${esc(g.name)} · ${g.mode} ${diagnosticBadge([...new Set(parallelIds(g).flatMap(id=>byBlock[id]||[]))])}</strong><span><button data-flow-move="-1" data-flow-id="${g.id}" aria-label="병렬 구간 위로">↑</button><button data-flow-move="1" data-flow-id="${g.id}" aria-label="병렬 구간 아래로">↓</button></span></header><div class="parallel-columns">${g.lanes.map((l,i)=>`<div><small>${esc(l.name)} · ${esc(audienceRoles(room.content.find(b=>b.id===g.steps[0].cells[i].blockId)).join(', '))}</small>${g.steps.map(s=>s.cells[i].hold?'<div class="parallel-hold">↳ 이전 화면 유지</div>':`<button type="button" class="parallel-cell ${roleFilter&&!roleVisible(room,room.content.find(b=>b.id===s.cells[i].blockId),roleFilter)?'role-dimmed':''} ${selected===s.cells[i].blockId?'selected':''}" data-select="${s.cells[i].blockId}">${esc(room.content.find(b=>b.id===s.cells[i].blockId)?.title||'콘텐츠')} ${diagnosticBadge(byBlock[s.cells[i].blockId])}</button>`).join('')}</div>`).join('')}</div></article>`;}
export function parallelFields(room,b){const g=parallelGroup(room,b.id);if(!g)return '';return `<section id="parallel-settings"><h3>병렬 구간 설정</h3><label class="field">구간 이름<input data-parallel-name value="${esc(g.name)}"></label><label class="field">합류 조건<select data-parallel-mode>${options({AND:'모든 경로 완료 후 합류 (AND)',OR:'한 경로 완료 즉시 합류 (OR)'},g.mode)}</select></label><p class="muted">각 경로는 순서대로 진행합니다. 화면 유지는 해당 단계의 다른 경로가 끝날 때까지 이전 화면을 읽기 전용으로 보여줍니다.</p><div class="parallel-columns">${g.lanes.map((l,i)=>`<div><strong>${esc(l.name)}</strong>${roleNames(room).map(r=>`<label class="check"><input type="checkbox" data-lane-role="${i}" data-role="${esc(r)}" ${audienceRoles(room.content.find(b=>b.id===g.steps[0].cells[i].blockId)).includes(r)?'checked':''}>${esc(r)}</label>`).join('')}</div>`).join('')}</div>${g.steps.map((s,n)=>`<div class="parallel-step"><strong>단계 ${n+1}</strong><div class="parallel-columns">${s.cells.map((c,i)=>`<label>${esc(g.lanes[i].name)}<select data-cell-step="${n}" data-cell-lane="${i}" ${n===0?'disabled':''}>${options({new:'새 콘텐츠',hold:'이전 화면 유지'},c.hold?'hold':'new')}</select></label>`).join('')}</div></div>`).join('')}<div class="actions"><button class="btn small" data-parallel-add>병렬 단계 추가</button>${g.steps.length>1?'<button class="btn small" data-parallel-remove-step>마지막 단계 삭제</button>':''}<button class="btn small" data-parallel-delete>구간 삭제</button></div></section>`;}
function removeBlocks(room,ids){const qrIds=(room.qrMissions||[]).filter(m=>ids.includes(m.blockId)).flatMap(m=>[m.id,...m.codes.map(q=>q.id)]);room.content=room.content.filter(b=>!ids.includes(b.id));room.qrMissions=(room.qrMissions||[]).filter(m=>!ids.includes(m.blockId));for(const b of room.content)b.unlock.conditions=b.unlock.conditions.filter(c=>!ids.includes(c.blockId)&&!qrIds.includes(c.blockId));if(ids.includes(room.rules.finalBlockId)){room.rules.finalBlockId=null;room.rules.finishMode='all';}}
export function mountParallelFields(root,room,b,changed,redraw,select){const el=root.querySelector('#parallel-settings'),g=parallelGroup(room,b.id);if(!el||!g)return;
 el.insertAdjacentHTML('beforeend',`<label class="field">선택한 칸의 콘텐츠 유형<select data-parallel-type>${options(BLOCK_TYPES,b.type)}</select></label>`);
 el.oninput=e=>{e.stopPropagation();if(e.target.hasAttribute('data-parallel-name')){g.name=e.target.value;changed();}};
 el.onchange=async e=>{e.stopPropagation();const t=e.target;
  if(t.hasAttribute('data-parallel-type')){
   if(b.type==='question'&&b.questionType==='qr'&&t.value!=='question'){
    if(!await confirmDialog('콘텐츠 유형을 바꿀까요?','이 문제의 QR 설정과 이를 참조하는 QR 조건이 삭제됩니다.')){redraw();return;}
    const missions=(room.qrMissions||[]).filter(m=>m.blockId===b.id),refs=missions.flatMap(m=>[m.id,...m.codes.map(q=>q.id)]);
    room.qrMissions=(room.qrMissions||[]).filter(m=>m.blockId!==b.id);for(const item of room.content)item.unlock.conditions=item.unlock.conditions.filter(c=>!refs.includes(c.blockId));delete b.qrMissionId;b.questionType='short';
   }
   b.type=t.value;if(!displayTypesFor(b.type)[b.display])b.display='card';
  }
  else if(t.hasAttribute('data-parallel-mode'))g.mode=t.value;
  else if(t.hasAttribute('data-lane-role')){const i=Number(t.dataset.laneRole),roles=audienceRoles(room.content.find(b=>b.id===g.steps[0].cells[i].blockId));laneRoles(room,g,i,t.checked?[...new Set([...roles,t.dataset.role])]:roles.filter(r=>r!==t.dataset.role));}
  else if(t.hasAttribute('data-cell-step')){const n=Number(t.dataset.cellStep),i=Number(t.dataset.cellLane),c=g.steps[n].cells[i];if(t.value==='hold'){if(g.steps[n].cells[1-i].hold){toast('같은 단계의 두 화면을 모두 유지할 수 없습니다.',true);redraw();return;}if(!await confirmDialog('이전 화면을 유지할까요?','이 칸의 콘텐츠와 연결된 QR·외부 참조 조건을 삭제하고 이전 화면을 읽기 전용으로 유지합니다.')){redraw();return;}removeBlocks(room,[c.blockId]);g.steps[n].cells[i]={hold:true};select(g.steps[0].cells[i].blockId);}else{const first=room.content.find(b=>b.id===g.steps[0].cells[i].blockId),block=newBlock('story');block.stageId=first.stageId;block.assignment.visibleRoles=[...audienceRoles(first)];room.content.splice(Math.max(...parallelIds(g).map(id=>room.content.findIndex(b=>b.id===id)))+1,0,block);g.steps[n].cells[i]={blockId:block.id};const ids=parallelIds(g),start=room.content.findIndex(b=>ids.includes(b.id)),ordered=ids.map(id=>room.content.find(b=>b.id===id));room.content=room.content.filter(b=>!ids.includes(b.id));room.content.splice(start,0,...ordered);select(block.id);}}
  else return;changed();redraw();};
 el.onclick=async e=>{e.stopPropagation();try{if(e.target.closest('[data-parallel-add]')){addParallelStep(room,g,b.stageId,newBlock);changed();redraw();}else if(e.target.closest('[data-parallel-delete]')&&await confirmDialog('병렬 구간을 삭제할까요?','이 구간의 모든 콘텐츠와 QR, 참조 조건을 제거합니다.')){removeBlocks(room,parallelIds(g));room.parallelGroups=room.parallelGroups.filter(x=>x!==g);select(room.content[0]?.id);changed();redraw();}else if(e.target.closest('[data-parallel-remove-step]')&&await confirmDialog('마지막 병렬 단계를 삭제할까요?','해당 단계의 콘텐츠와 QR, 참조 조건을 제거합니다.')){removeBlocks(room,g.steps.pop().cells.map(c=>c.blockId).filter(Boolean));select(g.steps[0].cells[0].blockId);changed();redraw();}}catch(error){toast(error.message,true);}};
}
