import {qrPrintItems,qrPrintLayout} from '../core/qr-print.js';
import {qrUrl} from '../core/qr.js';
import {qrLibrary} from './qr.js';
import {esc,modal} from './dom.js';
export const QR_PRINT_CSS=`@page{size:A4 portrait;margin:0}*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;color:#000;background:#ddd}.qr-print-sheet{width:210mm;height:297mm;padding:10mm;background:#fff;margin:10px auto;break-after:page;page-break-after:always;overflow:hidden}.qr-print-sheet:last-child{break-after:auto;page-break-after:auto}.qr-print-grid{display:grid;gap:4mm;align-content:start;justify-content:start}.qr-print-card{padding:3mm;text-align:center;background:#fff;break-inside:avoid;page-break-inside:avoid;display:flex;flex-direction:column;align-items:center;color:#000;outline:0.2mm dashed transparent;outline-offset:-0.2mm}.qr-print-card.cut{outline-color:#999}.qr-print-card svg{display:block;flex-shrink:0;max-width:none;max-height:none}.qr-print-number{font-size:10pt;line-height:6mm;height:6mm}.qr-print-name{font-size:11pt;line-height:6mm;max-height:12mm;overflow:hidden;overflow-wrap:anywhere;width:100%}@media print{body{background:#fff}.qr-print-sheet{margin:0}}`;
export function qrPrintPages(layout,svgs,moduleCounts){return layout.pages.map(page=>`<section class="qr-print-sheet"><div class="qr-print-grid" style="grid-template-columns:repeat(${layout.columns},${layout.width}mm)">${page.map(q=>{const side=layout.qrMm*(1+8/moduleCounts[q.id]);return `<article class="qr-print-card ${layout.cuts?'cut':''}" style="width:${layout.width}mm;height:${layout.height}mm"><div style="width:${side}mm;height:${side}mm">${svgs[q.id]}</div>${layout.numbers?`<span class="qr-print-number">QR ${String(q.number).padStart(2,'0')}</span>`:''}${layout.names?`<span class="qr-print-name">${esc(q.name)}</span>`:''}</article>`;}).join('')}</div></section>`).join('');}
export function printQrPages(html){
 const frame=document.createElement('iframe');frame.title='QR 인쇄';frame.className='qr-print-frame';frame.style.cssText='position:fixed;width:0;height:0;border:0;left:-9999px';
 frame.onload=()=>{frame.contentWindow.onafterprint=()=>frame.remove();frame.contentWindow.focus();frame.contentWindow.print();setTimeout(()=>frame.remove(),300000);};
 frame.srcdoc=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>QR 인쇄</title><style>${QR_PRINT_CSS}</style></head><body>${html}</body></html>`;document.body.append(frame);
}
export async function qrPrintDialog(room){
 const items=qrPrintItems(room);const d=modal(`<div class="modal-body qr-print-dialog"><h2>QR 인쇄</h2><p>같은 QR을 여러 장 인쇄합니다. QR과 콘텐츠는 변경되지 않습니다.</p><label class="check"><input type="checkbox" data-print-all checked>전체 선택</label><div class="qr-print-list">${items.map(q=>`<div class="qr-print-option"><label class="check"><input type="checkbox" data-print-id="${q.id}" checked>QR ${String(q.number).padStart(2,'0')} · ${esc(q.name)}${q.active?'':' (비활성)'}</label><small>${esc(q.stage)} · ${esc(q.blockTitle)}</small><label>수량 <input type="number" data-print-quantity="${q.id}" value="1" min="1" max="30"></label></div>`).join('')||'<p>등록된 QR이 없습니다.</p>'}</div>
 <div class="actions"><label>선택한 QR 모두 수량 <input type="number" data-print-bulk value="1" min="1" max="30"></label><button class="btn" data-print-apply>수량 적용</button></div>
 <label class="field"><span>QR 크기</span><select data-print-size><option value="4">작게 · 4cm</option><option value="6" selected>보통 · 6cm</option><option value="8">크게 · 8cm</option><option value="custom">직접 입력</option></select></label><label data-print-custom-label hidden>QR 크기 (cm) <input data-print-custom type="number" min="3" max="10" step="0.1" value="6"></label>
 <div class="story-export-options"><label class="check"><input type="checkbox" data-print-names checked>QR 이름 표시</label><label class="check"><input type="checkbox" data-print-numbers checked>QR 번호 표시</label><label class="check"><input type="checkbox" data-print-cuts checked>절취선 표시</label></div>
 <p class="muted">크기는 QR 무늬 영역 기준이며 흰 여백이 추가됩니다. A4·배율 100%·브라우저 머리글/바닥글 끄기로 인쇄하세요.</p><div class="actions"><button class="btn" data-print-preview>인쇄 미리보기</button><button class="btn primary" data-print-go disabled>인쇄하기</button></div><p data-print-status role="status"></p><div class="qr-print-preview" data-print-pages></div></div>`);
 const status=d.querySelector('[data-print-status]'),svgs={},moduleCounts={};let html='';
 const invalidate=()=>{html='';d.querySelector('[data-print-go]').disabled=true;d.querySelector('[data-print-pages]').innerHTML='';status.textContent='옵션을 반영하려면 인쇄 미리보기를 누르세요.';};
 d.onchange=e=>{if(e.target.hasAttribute('data-print-all'))d.querySelectorAll('[data-print-id]').forEach(el=>el.checked=e.target.checked);const boxes=[...d.querySelectorAll('[data-print-id]')],all=d.querySelector('[data-print-all]');all.checked=boxes.length>0&&boxes.every(el=>el.checked);all.indeterminate=boxes.some(el=>el.checked)&&!all.checked;d.querySelector('[data-print-custom-label]').hidden=d.querySelector('[data-print-size]').value!=='custom';invalidate();};
 d.oninput=e=>{if(e.target.type==='number')invalidate();};
 d.querySelector('[data-print-apply]').onclick=()=>{const n=Number(d.querySelector('[data-print-bulk]').value);if(!Number.isInteger(n)||n<1||n>30){status.textContent='수량은 1~30개로 입력하세요.';return;}for(const el of d.querySelectorAll('[data-print-id]:checked'))d.querySelector(`[data-print-quantity="${el.dataset.printId}"]`).value=n;invalidate();};
 d.querySelector('[data-print-preview]').onclick=async()=>{try{
  await qrLibrary('qrcode-generator');if(!d.open)return;
  const selected=[...d.querySelectorAll('[data-print-id]:checked')].map(el=>el.dataset.printId);for(const q of items.filter(q=>selected.includes(q.id)))if(!svgs[q.id]){const code=globalThis.qrcode(0,'M');code.addData(qrUrl(q.token,room.qrBaseUrl||location.origin+location.pathname));code.make();moduleCounts[q.id]=code.getModuleCount();svgs[q.id]=code.createSvgTag({cellSize:1,margin:4,scalable:true}).replace('<svg ','<svg style="width:100%;height:100%" ');}
  const size=d.querySelector('[data-print-size]').value,layout=qrPrintLayout(items,{selected,quantities:Object.fromEntries([...d.querySelectorAll('[data-print-quantity]')].map(el=>[el.dataset.printQuantity,Number(el.value)])),size:Number(size==='custom'?d.querySelector('[data-print-custom]').value:size),names:d.querySelector('[data-print-names]').checked,numbers:d.querySelector('[data-print-numbers]').checked,cuts:d.querySelector('[data-print-cuts]').checked},moduleCounts);
  html=qrPrintPages(layout,svgs,moduleCounts);d.querySelector('[data-print-pages]').innerHTML=`<iframe title="A4 인쇄 미리보기" class="qr-print-preview-frame"></iframe>`;const preview=d.querySelector('.qr-print-preview-frame');preview.onload=()=>{const fit=()=>{if(preview.contentDocument?.body)preview.contentDocument.body.style.zoom=Math.min(1,(preview.clientWidth-12)/(210/25.4*96));};fit();preview.contentWindow.onresize=fit;};preview.srcdoc=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><style>${QR_PRINT_CSS}</style></head><body>${html}</body></html>`;status.textContent=layout.total?`${layout.total}개 · A4 ${layout.pages.length}페이지`:'인쇄할 QR을 선택하세요.';d.querySelector('[data-print-go]').disabled=!layout.total;
 }catch(error){invalidate();status.textContent=error.message;}};
 d.querySelector('[data-print-go]').onclick=()=>{if(html)printQrPages(html);};
}
