export const qrToken=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('');
export const newQr=()=>({id:crypto.randomUUID(),token:qrToken(),name:'새 QR',active:true});
export const newQrMission=()=>({id:crypto.randomUUID(),name:'QR 미션',active:true,scope:'team',mode:'ANY',count:1,assignment:{mode:'all',member:1,role:'조장'},result:{type:'condition',targetId:null},codes:[newQr()]});
export function readQr(value){const s=String(value||'').trim();if(/^[a-f0-9]{64}$/.test(s))return s;try{const u=new URL(s);const token=u.searchParams.get('qr');return ['http:','https:'].includes(u.protocol)&&/^[a-f0-9]{64}$/.test(token||'')?token:null;}catch{return null;}}
export function qrUrl(token,base){if(!readQr(token))throw Error('QR 식별자가 올바르지 않습니다.');const u=new URL(base);if(!['http:','https:'].includes(u.protocol))throw Error('http(s) 사이트 주소를 입력하세요.');u.hash='';u.search='';u.searchParams.set('qr',token);return u.href;}
export function qrDone(m,scans,members){const unique=[...new Map(scans.map(s=>[s.qrId,s])).values()];const total=m.codes.filter(q=>q.active).length;if(!total)return false;if(m.mode==='UNIQUE_MEMBER')return members.length>0&&members.every(p=>unique.some(s=>s.member===p.member));return unique.length>=(m.mode==='ALL'?total:m.mode==='N_OF_M'?m.count:1);}
export function qrTestState(room,session,member){return (room.qrMissions||[]).filter(m=>m.active).map(m=>{const scans=(session.qrScans||[]).filter(s=>s.missionId===m.id&&(room.playMode==='individual'||m.scope==='student'?s.member===member:true)&&m.codes.some(q=>q.id===s.qrId&&q.active));return {...m,found:scans.length,total:m.codes.filter(q=>q.active).length,done:qrDone(m,scans,room.playMode==='team'&&m.scope==='team'?session.members:[session.members.find(p=>p.member===member)])};});}
export function qrTestEvents(room,session,member){const events=[];for(const m of qrTestState(room,session,member)){for(const s of (session.qrScans||[]).filter(s=>s.missionId===m.id&&(m.scope==='team'||s.member===member)))events.push({blockId:s.qrId,type:'qr_scanned',member:s.member,role:s.role});if(m.done)events.push({blockId:m.id,type:'qr_complete',member:0,role:''});}return events;}
export function scanTestQr(room,session,member,id){if(session.finishedAt)throw Error('이미 완료된 테스트입니다.');const m=(room.qrMissions||[]).find(m=>m.codes.some(q=>q.id===id));const q=m?.codes.find(q=>q.id===id),actor=session.members.find(p=>p.member===member);if(!m?.active||!q?.active||!actor)throw Error('사용할 수 없는 QR입니다.');if(m.assignment.mode==='member'&&m.assignment.member!==member||m.assignment.mode==='role'&&m.assignment.role!==actor.role)throw Error('해당 참가자에게 배정된 QR이 아닙니다.');session.qrScans??=[];if(session.qrScans.some(s=>s.qrId===id))return false;session.qrScans.push({qrId:id,missionId:m.id,member,role:actor.role});return true;}
